/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;

import com.itextpdf.text.Document;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
 import java.sql.*;
import java.util.Base64;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class billing_page extends javax.swing.JFrame {

    /**
     * Creates new form billing_page
     */
    public billing_page() {
        initComponents();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        Date date1 = new Date();
        date.setText(sdf.format(date1));
        
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("HH:mm:ss");
             LocalDateTime ldf =  LocalDateTime.now();
        time.setText(dtf.format(ldf));
     }
 public static String decrypt(String encryptedcode , String secretkey) throws Exception
    {
        Cipher cipher = Cipher.getInstance("AES");
        SecretKeySpec  secrectkeyspec = new SecretKeySpec(secretkey.getBytes(),"AES");
        cipher.init(Cipher.DECRYPT_MODE,secrectkeyspec);
        byte[] decodedbyte = Base64.getDecoder().decode(encryptedcode);
        byte[] encryptbyte = cipher.doFinal(decodedbyte);
        return new String(encryptbyte);
    }
    private final String SECRET_KEY = "1234567890123456";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        billing_tbl = new javax.swing.JTable();
        back = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        close = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        save = new javax.swing.JButton();
        buyer_name = new javax.swing.JTextField();
        mobile_no = new javax.swing.JTextField();
        email_id = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        product_id = new javax.swing.JTextField();
        paid_amt = new javax.swing.JTextField();
        balance_amt = new javax.swing.JTextField();
        product_name = new javax.swing.JTextField();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Billing page");
        setMinimumSize(new java.awt.Dimension(1114, 697));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 107, 1114, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 1114, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing icon.png"))); // NOI18N
        jLabel1.setText("BILLING PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 359, 1108, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DATE :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 50, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("TIME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 32, 50, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("BUYER DETAILS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 116, 110, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PRODUCT DETAILS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 226, 130, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("AMOUNT DETAILS");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 368, 130, -1));

        billing_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ", "PRICE ", "QTY", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        billing_tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billing_tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(billing_tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 396, -1, 258));

        back.setBackground(new java.awt.Color(255, 204, 51));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("BUEYR NAME :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("MOBILE NO. :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("EMAIL ID :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("PRODUCT ID :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("PRODUCT NAME :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("PRICE :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("QTY :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, -1, -1));

        add.setBackground(new java.awt.Color(204, 255, 204));
        add.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        add.setText("ADD");
        add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("TOTAL :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 60, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("PAID AMOUNT :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("BALANCE AMOUNT :");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, -1));

        close.setBackground(new java.awt.Color(255, 0, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 600, 120, 30));

        clear.setBackground(new java.awt.Color(255, 204, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 120, 30));

        delete.setBackground(new java.awt.Color(255, 0, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 430, 120, 30));

        save.setBackground(new java.awt.Color(0, 153, 255));
        save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        save.setText("SAVE");
        save.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 490, 120, 30));

        buyer_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(buyer_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, 30));

        mobile_no.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mobile_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_noActionPerformed(evt);
            }
        });
        mobile_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mobile_noKeyPressed(evt);
            }
        });
        getContentPane().add(mobile_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 200, 30));

        email_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        email_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_idActionPerformed(evt);
            }
        });
        getContentPane().add(email_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 230, 30));

        total.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 200, 30));

        price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 280, 120, 30));

        qty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyActionPerformed(evt);
            }
        });
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, 100, 30));

        product_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        product_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_idActionPerformed(evt);
            }
        });
        getContentPane().add(product_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 140, 30));

        paid_amt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paid_amt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paid_amtActionPerformed(evt);
            }
        });
        getContentPane().add(paid_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 500, 200, 30));

        balance_amt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(balance_amt, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 200, 30));

        product_name.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(product_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 200, 30));

        time.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 30, 140, 30));

        date.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 140, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrond image.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyActionPerformed

    private void mobile_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_noActionPerformed
         String cell = mobile_no.getText();
        
        try(Connection conn = JDBC.con();
        PreparedStatement pst = conn.prepareStatement("sp_jeomart_buyer_getone ?"))
                {
                   pst.setString(1, cell);
                   ResultSet rs = pst.executeQuery();
                   if(rs.next())
                   {
                       String name = rs.getString("buyer_name");
                       String mailid = rs.getString("email_id");
                       buyer_name.setText(name);
                       email_id .setText(mailid);
                   }
                }
                catch(Exception e)
                        {
                        JOptionPane.showMessageDialog(this,e);
                        }
    }//GEN-LAST:event_mobile_noActionPerformed

    private void email_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_idActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
       this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void mobile_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobile_noKeyPressed
       
        
    }//GEN-LAST:event_mobile_noKeyPressed

    private void product_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_idActionPerformed
        String id = product_id.getText();
          try(Connection conn = JDBC.con();
        PreparedStatement pst = conn.prepareStatement("jemart_product_getbyid ?"))
                {
                   pst.setString(1, id);
                   ResultSet rs = pst.executeQuery();
                   if(rs.next())
                   {
                       String name = rs.getString("product_name");
                       String price1 = decrypt(rs.getString("price"),SECRET_KEY);
                       product_name.setText(name);
                       price .setText(price1);
                   }
                }
                catch(Exception e)
                        {
                        JOptionPane.showMessageDialog(this,e);
                        }
        
    }//GEN-LAST:event_product_idActionPerformed
     double finaltotal = 0;
     double rate = 0;
     int qnty = 1;
     double tot = 0;
     int row=0;
     double tot1 =-1;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        rate = Double.parseDouble(price.getText());
        qnty = Integer.parseInt(qty.getText());
        tot = rate*qnty;
        finaltotal = finaltotal+tot;
        
        DefaultTableModel  dtm = (DefaultTableModel)billing_tbl.getModel();
        dtm.addRow(new Object[]{product_name.getText(),rate,qnty,tot});
        String Total = String.valueOf(finaltotal);
        total.setText(Total);
        
    }//GEN-LAST:event_addActionPerformed

    private void paid_amtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paid_amtActionPerformed
        String pamt = paid_amt.getText();
        int PAMT = Integer.parseInt(pamt);
        finaltotal = PAMT - finaltotal;
        String Ramt = String.valueOf(finaltotal);
        balance_amt.setText(Ramt);
        balance_amt.setEditable(false);
    }//GEN-LAST:event_paid_amtActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
          DefaultTableModel  dtm = (DefaultTableModel)billing_tbl.getModel();
          if(billing_tbl.getSelectedRowCount()==1)
          {
          dtm.removeRow(billing_tbl.getSelectedRow());
          finaltotal= finaltotal-tot1;
            String Total = String.valueOf(finaltotal);
           total.setText(Total);
          }
          
    }//GEN-LAST:event_deleteActionPerformed

    private void billing_tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billing_tblMouseClicked
        row = billing_tbl.rowAtPoint(evt.getPoint());
        tot1 = (double)  billing_tbl.getValueAt(row, 3);
    }//GEN-LAST:event_billing_tblMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
             com.itextpdf.text.Document doc = new com.itextpdf.text.Document();
        }
        try {
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream(path+""+date.getText()+".pdf"));
            doc.open();
           Paragraph p1 = new Paragraph("                        BILL COPY                            "+"\n\n");
           doc.add(p1);
            Paragraph p2 = new Paragraph("Date & Time:"+date.getText()+"  "+time.getText()+"\n\n");
           doc.add(p2);
            Paragraph p3 = new Paragraph("Buyer name :"+buyer_name.getText()+"\n Mobile :"+mobile_no.getText()+"\nEmail ID :"+email_id.getText()+"\n\n");
           doc.add(p3);
           
         
            PdfPTable tbl = new PdfPTable(4);
            {
                tbl.addCell("PRODUCT NAME");
                tbl.addCell("PRICE");
                tbl.addCell("QTY");
                tbl.addCell("TOTAL");
                for(int i = 0 ; i <billing_tbl.getRowCount();i++)
                {
                 String n = billing_tbl.getValueAt(i,0).toString();
                  String r = billing_tbl.getValueAt(i,1).toString();
                   String f = billing_tbl.getValueAt(i,2).toString();
                    String m = billing_tbl.getValueAt(i,3).toString();
                    tbl.addCell(n);
                    tbl.addCell(r);
                    tbl.addCell(f);
                    tbl.addCell(m);
                    System.out.println("\n\n");
                   
                }
                doc.add(tbl);
                  Paragraph p4 = new Paragraph("Total amt :"+total.getText()+"\n"+"Paid amt :" +paid_amt.getText()+"\n"+"Return amt :"+balance_amt.getText()+"\n\n ***Thanks for your purchase "+"\n"+" Visite Again***");
           doc.add(p4);
           JOptionPane.showMessageDialog(this,"Bill Generated");
           doc.close();
                
              
            }
               
  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.setVisible(false);
         new billing_page().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(billing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(billing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(billing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(billing_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new billing_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton back;
    private javax.swing.JTextField balance_amt;
    private javax.swing.JTable billing_tbl;
    private javax.swing.JTextField buyer_name;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JLabel date;
    private javax.swing.JButton delete;
    private javax.swing.JTextField email_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField mobile_no;
    private javax.swing.JTextField paid_amt;
    private javax.swing.JTextField price;
    private javax.swing.JTextField product_id;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JLabel time;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
