/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;

import java.awt.Image;
import java.io.File;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import jeo_mart.JDBC;

/**
 *
 * @author ASUS
 */
public class Buyer_update_page extends javax.swing.JFrame {

    /**
     * Creates new form Buyer_update_page
     */
    public Buyer_update_page() {
        initComponents();
    }

    private boolean isExists(String no) {
        try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_buyer_isExists ?")) {
            pst.setString(1, no);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                return rs.getInt(1) > 0;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bid = new javax.swing.JTextField();
        bname = new javax.swing.JTextField();
        bmail_id = new javax.swing.JTextField();
        bphoto_path = new javax.swing.JTextField();
        bmobile_no = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        baddress = new javax.swing.JTextArea();
        bphoto = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        update = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buyer Update page");
        setMaximumSize(new java.awt.Dimension(1110, 636));
        setMinimumSize(new java.awt.Dimension(1110, 636));
        setPreferredSize(new java.awt.Dimension(1110, 636));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon.png"))); // NOI18N
        jLabel1.setText("BUYER UPDATE PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("BUYER NAME :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("EMAIL ID :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("MOBILE NO :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setText("ADDRESS :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel6.setText("PHOTO  :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel7.setText("BUYER ID :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel8.setText("PHOTO PATH :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 540, -1, -1));

        bid.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        bid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bidActionPerformed(evt);
            }
        });
        bid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bidKeyPressed(evt);
            }
        });
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 292, 34));

        bname.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(bname, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 292, 34));

        bmail_id.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(bmail_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 292, 34));

        bphoto_path.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(bphoto_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 292, 34));

        bmobile_no.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        bmobile_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bmobile_noKeyPressed(evt);
            }
        });
        getContentPane().add(bmobile_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 292, 34));

        baddress.setColumns(20);
        baddress.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        baddress.setRows(5);
        jScrollPane2.setViewportView(baddress);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 292, -1));
        getContentPane().add(bphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 136, 144));

        back.setBackground(new java.awt.Color(255, 204, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(995, 28, 85, 35));

        clear.setBackground(new java.awt.Color(255, 204, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 120, 35));

        update.setBackground(new java.awt.Color(0, 204, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 370, 120, 35));

        close.setBackground(new java.awt.Color(255, 0, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 510, 120, 35));

        jLabel9.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        jLabel9.setText(" * Press enter after entered the Buyer ID *");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 230, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrond image.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.setVisible(false);
        new Buyer_update_page().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void bidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bidKeyPressed


    }//GEN-LAST:event_bidKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String BID = bid.getText();
        String BNAME = bname.getText();
        String BMAIL_ID = bmail_id.getText();
        String BMOBILE = bmobile_no.getText();
        String BADDRESS = baddress.getText();
        String imgpath = "";
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Image File", "JPG", "JPEG", "PNG"));
        int resultvalue = fileChooser.showOpenDialog(this);
        if (resultvalue == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            imgpath = file.getAbsolutePath();
            bphoto_path.setText(file.getName());
            bphoto.setIcon(new ImageIcon(new ImageIcon(imgpath).getImage().getScaledInstance(bphoto.getWidth(), bphoto.getHeight(), Image.SCALE_SMOOTH)));
        }

        if (!BID.isEmpty() && !BNAME.isEmpty() && !BMAIL_ID.isEmpty() && !BMOBILE.isEmpty() && !BADDRESS.isEmpty() && !imgpath.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_buyer_update ?,?,?,?,?,?")) {
                pst.setString(1, BID);
                pst.setString(2, BNAME);
                pst.setString(3, BMAIL_ID);
                pst.setString(4, BMOBILE);
                pst.setString(5, BADDRESS);
                pst.setString(6, imgpath);
                int result = pst.executeUpdate();
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Datas Updated");
                } else {
                    JOptionPane.showMessageDialog(this, "Datas Can't Update");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Enter All Datas");
        }

    }//GEN-LAST:event_updateActionPerformed

    private void bidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bidActionPerformed

    private void bmobile_noKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bmobile_noKeyPressed
        String BMOBILE = bmobile_no.getText();
//        if (!BMOBILE.isEmpty()) {
            if (isExists(BMOBILE)) {
                try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_buyer_getone ?")) {
                    pst.setString(1, BMOBILE);
                    ResultSet rs = pst.executeQuery();
                    if (rs.next()) {
                        String bid1 = rs.getString("buyer_id");
                        bid.setText(bid1);
                        String buyer_name = rs.getString("buyer_name");
                        bname.setText(buyer_name);
                        String mail_id = rs.getString("email_id");
                        bmail_id.setText(mail_id);
                        String address = rs.getString("address");
                        baddress.setText(address);
                        String imgpath = rs.getString("photo_path");
                        bphoto_path.setText(imgpath);
                        bphoto.setIcon(new ImageIcon(new ImageIcon(imgpath).getImage().getScaledInstance(bphoto.getWidth(), bphoto.getHeight(), Image.SCALE_SMOOTH)));
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e);
                }

            }
//else
                
//             JOptionPane.showMessageDialog(this," Enter Mobile Number");
            
           
                
               
        


    }//GEN-LAST:event_bmobile_noKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buyer_update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buyer_update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buyer_update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buyer_update_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buyer_update_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea baddress;
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bmail_id;
    private javax.swing.JTextField bmobile_no;
    private javax.swing.JTextField bname;
    private javax.swing.JLabel bphoto;
    private javax.swing.JTextField bphoto_path;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
