/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;
import java.sql.*;
import javax.swing.*;
/**
 *
 * @author ASUS
 */
public class forgot_and_reset extends javax.swing.JFrame {

    /**
     * Creates new form forgot_and_reset
     */
    public forgot_and_reset() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        close = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        user_id = new javax.swing.JTextField();
        sec_question = new javax.swing.JTextField();
        sec_answer = new javax.swing.JTextField();
        old_password = new javax.swing.JTextField();
        new_password = new javax.swing.JTextField();
        conform_password = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        get_question = new javax.swing.JButton();
        get_pwd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Forgot and Reset");
        setMaximumSize(new java.awt.Dimension(641, 674));
        setMinimumSize(new java.awt.Dimension(641, 674));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forgot icon.png"))); // NOI18N
        jLabel1.setText("FORGOT AND RESET PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 6, -1, -1));

        back.setBackground(new java.awt.Color(255, 204, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, -1));

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 110, 34));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 110, 34));

        reset.setBackground(new java.awt.Color(0, 204, 255));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reset.setText("RESET");
        reset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, 110, 34));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 134, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SECURITY QUESTION :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 237, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 228, 37, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NEW PASSWORD :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 475, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("OLD PASSWORD :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 401, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CONFORM PASSWORD :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 545, -1, -1));

        user_id.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(user_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 131, 230, -1));

        sec_question.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(sec_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 234, 230, -1));

        sec_answer.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(sec_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 293, 230, -1));

        old_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        old_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                old_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 398, 230, -1));

        new_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 472, 230, -1));

        conform_password.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        conform_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conform_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(conform_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 542, 230, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SECURITY ANSWER :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 296, -1, -1));

        get_question.setBackground(new java.awt.Color(204, 255, 204));
        get_question.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        get_question.setText("GET");
        get_question.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_question.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get_question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_questionActionPerformed(evt);
            }
        });
        getContentPane().add(get_question, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 61, -1));

        get_pwd.setBackground(new java.awt.Color(204, 255, 204));
        get_pwd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        get_pwd.setText("GET");
        get_pwd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get_pwd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_pwdActionPerformed(evt);
            }
        });
        getContentPane().add(get_pwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 342, 60, -1));

        jLabel9.setBackground(new java.awt.Color(255, 153, 0));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void old_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_old_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_old_passwordActionPerformed

    private void conform_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conform_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conform_passwordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
         new log_in_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       this.setVisible(false);
          new forgot_and_reset().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void get_questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_questionActionPerformed
        String uid = user_id.getText();
        if (!uid.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_admin_getquestion ?")) {
                pst.setString(1, uid);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String sec_ques = rs.getString("sec_question");
                    sec_question.setText(sec_ques);
                } else {
                    JOptionPane.showMessageDialog(this, "Invalid User-id");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Enter User-id");
        }
    }//GEN-LAST:event_get_questionActionPerformed

    private void get_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_pwdActionPerformed
       String sec_ans = sec_answer.getText();
        if (!sec_ans.isEmpty()) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_admin_getpassword ?")) {
                pst.setString(1, sec_ans);
                ResultSet rs = pst.executeQuery();
                if (rs.next()) {
                    String pwd = rs.getString("password");
                    old_password.setText(pwd);
                } else {
                    JOptionPane.showMessageDialog(this, "Incorrect Security Answer");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Enter Security Answer");
        }
    }//GEN-LAST:event_get_pwdActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        String uid = user_id.getText();
        String sec_ques = sec_question.getText();
        String sec_ans = sec_answer.getText();
        String old_pwd = old_password.getText();
        String new_pwd = new_password.getText();
        String conform_pwd = conform_password.getText();
        if (!uid.isEmpty() && !sec_ques.isEmpty() && !sec_ans.isEmpty() && !old_pwd.isEmpty() && !conform_pwd.isEmpty()
                && !new_pwd.isEmpty() && !(old_pwd.equals(new_pwd)) && new_pwd.equals(conform_pwd)) {
            try (Connection conn = JDBC.con(); PreparedStatement pst = conn.prepareStatement("sp_jeomart_admin_updatepassword ?,?")) {
                pst.setString(1, uid);
                pst.setString(2, conform_pwd);
                int result = pst.executeUpdate();
                if (result == 1) {
                    JOptionPane.showMessageDialog(this, "Password Updated");
                    this.setVisible(false);
                    new log_in_page().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Password Not Update");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Error");
        }
       
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgot_and_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgot_and_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgot_and_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgot_and_reset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgot_and_reset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JTextField conform_password;
    private javax.swing.JButton get_pwd;
    private javax.swing.JButton get_question;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField new_password;
    private javax.swing.JTextField old_password;
    private javax.swing.JButton reset;
    private javax.swing.JTextField sec_answer;
    private javax.swing.JTextField sec_question;
    private javax.swing.JTextField user_id;
    // End of variables declaration//GEN-END:variables
}
