/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;
import java.sql.*;
import javax.swing.*;


/**
 *
 * @author ASUS
 */
public class main_page extends javax.swing.JFrame {

    /**
     * Creates new form main_page
     */ 

     
    public main_page() {
        initComponents();

         
    }
  
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        baddbtn = new javax.swing.JButton();
        paddbtn = new javax.swing.JButton();
        bdeletebtn = new javax.swing.JButton();
        email = new javax.swing.JButton();
        bupdatebtn = new javax.swing.JButton();
        pdeletebtn = new javax.swing.JButton();
        pupdatesbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        bdetailsbtn = new javax.swing.JButton();
        pdetailsbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        otp = new javax.swing.JButton();
        qr = new javax.swing.JButton();
        barchart = new javax.swing.JButton();
        billingbtn4 = new javax.swing.JButton();
        barcode = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("main page");
        setMaximumSize(new java.awt.Dimension(1149, 646));
        setMinimumSize(new java.awt.Dimension(1149, 646));
        setPreferredSize(new java.awt.Dimension(1149, 646));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main page icon.png"))); // NOI18N
        jLabel1.setText("MAIN PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        baddbtn.setBackground(new java.awt.Color(255, 255, 153));
        baddbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        baddbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sing up icon.png"))); // NOI18N
        baddbtn.setText("ADD BUYERS");
        baddbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        baddbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baddbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                baddbtnComponentShown(evt);
            }
        });
        baddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(baddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, -1));

        paddbtn.setBackground(new java.awt.Color(204, 255, 204));
        paddbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        paddbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add product icon.png"))); // NOI18N
        paddbtn.setText("ADD PRODUCTS");
        paddbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        paddbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paddbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                paddbtnComponentShown(evt);
            }
        });
        paddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paddbtnActionPerformed(evt);
            }
        });
        getContentPane().add(paddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 249, -1));

        bdeletebtn.setBackground(new java.awt.Color(255, 255, 153));
        bdeletebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bdeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.jpg"))); // NOI18N
        bdeletebtn.setText("DELETE BUYER");
        bdeletebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdeletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdeletebtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                bdeletebtnComponentShown(evt);
            }
        });
        bdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(bdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 110, 260, 84));

        email.setBackground(new java.awt.Color(204, 204, 255));
        email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        email.setText("EMAIL PAGE");
        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        email.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                emailComponentShown(evt);
            }
        });
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 250, 90));

        bupdatebtn.setBackground(new java.awt.Color(255, 255, 153));
        bupdatebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bupdatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update icon.png"))); // NOI18N
        bupdatebtn.setText("BUYER UPDATES");
        bupdatebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bupdatebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bupdatebtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                bupdatebtnComponentShown(evt);
            }
        });
        bupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bupdatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(bupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 280, -1));

        pdeletebtn.setBackground(new java.awt.Color(204, 255, 204));
        pdeletebtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pdeletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete product icon.png"))); // NOI18N
        pdeletebtn.setText("DELETE PRODUCT");
        pdeletebtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pdeletebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pdeletebtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pdeletebtnComponentShown(evt);
            }
        });
        pdeletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdeletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(pdeletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 230, -1, -1));

        pupdatesbtn.setBackground(new java.awt.Color(204, 255, 204));
        pupdatesbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pupdatesbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product updates icon.jpg"))); // NOI18N
        pupdatesbtn.setText("PRODUCT UPDATES");
        pupdatesbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pupdatesbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pupdatesbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pupdatesbtnComponentShown(evt);
            }
        });
        pupdatesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pupdatesbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pupdatesbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 280, -1));

        exitbtn.setBackground(new java.awt.Color(255, 0, 0));
        exitbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 255, 255));
        exitbtn.setText("EXIT");
        exitbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });
        getContentPane().add(exitbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 260, 90));

        bdetailsbtn.setBackground(new java.awt.Color(255, 255, 153));
        bdetailsbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        bdetailsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buyer_details icon.png"))); // NOI18N
        bdetailsbtn.setText("BUYER DETAILS");
        bdetailsbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bdetailsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdetailsbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                bdetailsbtnComponentShown(evt);
            }
        });
        bdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(bdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 270, 87));

        pdetailsbtn.setBackground(new java.awt.Color(204, 255, 204));
        pdetailsbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        pdetailsbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product detail icon.png"))); // NOI18N
        pdetailsbtn.setText("PRODUCT DETAILS");
        pdetailsbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pdetailsbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pdetailsbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pdetailsbtnComponentShown(evt);
            }
        });
        pdetailsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdetailsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pdetailsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 270, -1));

        logoutbtn.setBackground(new java.awt.Color(255, 102, 102));
        logoutbtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        logoutbtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout icon.jpg"))); // NOI18N
        logoutbtn.setText("LOGOUT");
        logoutbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutbtn.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                logoutbtnComponentShown(evt);
            }
        });
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 280, 90));

        otp.setBackground(new java.awt.Color(204, 204, 255));
        otp.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        otp.setText("OTP PAGE");
        otp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        otp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                otpComponentShown(evt);
            }
        });
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });
        getContentPane().add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 250, 90));

        qr.setBackground(new java.awt.Color(204, 204, 255));
        qr.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        qr.setText("QR CODE PAGE");
        qr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qr.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                qrComponentShown(evt);
            }
        });
        qr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrActionPerformed(evt);
            }
        });
        getContentPane().add(qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 350, 250, 90));

        barchart.setBackground(new java.awt.Color(204, 204, 255));
        barchart.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        barchart.setText("BARCHART PAGE");
        barchart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barchart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barchart.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                barchartComponentShown(evt);
            }
        });
        barchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchartActionPerformed(evt);
            }
        });
        getContentPane().add(barchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 250, 90));

        billingbtn4.setBackground(new java.awt.Color(204, 204, 255));
        billingbtn4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        billingbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billing icon.png"))); // NOI18N
        billingbtn4.setText("BILLING");
        billingbtn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        billingbtn4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        billingbtn4.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                billingbtn4ComponentShown(evt);
            }
        });
        billingbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billingbtn4ActionPerformed(evt);
            }
        });
        getContentPane().add(billingbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 250, 90));

        barcode.setBackground(new java.awt.Color(204, 204, 255));
        barcode.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        barcode.setText("BARCODE PAGE");
        barcode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barcode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barcode.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                barcodeComponentShown(evt);
            }
        });
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        getContentPane().add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 250, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void baddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddbtnActionPerformed
       this.setVisible(false);
       new Buyer_add_page().setVisible(true);
    }//GEN-LAST:event_baddbtnActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
     int a = JOptionPane.showConfirmDialog(this,"Do you want to exit ?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0)
     {
         System.exit(a);
     }
    }//GEN-LAST:event_exitbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
         int a = JOptionPane.showConfirmDialog(this,"Do you want to Logout ?","Select",JOptionPane.YES_NO_OPTION);
     if(a==0)
     {
         this.setVisible(false);
         new  log_in_page().setVisible(true);
     }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void baddbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_baddbtnComponentShown
//        if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              bdetailsbtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_baddbtnComponentShown

    private void bdetailsbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bdetailsbtnComponentShown
//         if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              bupdatebtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_bdetailsbtnComponentShown

    private void bupdatebtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bupdatebtnComponentShown
//        if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              bdeletebtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_bupdatebtnComponentShown

    private void bdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdeletebtnActionPerformed
        this.setVisible(false);
        new buyer_delete().setVisible(true);
    }//GEN-LAST:event_bdeletebtnActionPerformed

    private void paddbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_paddbtnComponentShown
//          if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              pdetailsbtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_paddbtnComponentShown

    private void pdetailsbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pdetailsbtnComponentShown
//           if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              pupdatesbtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_pdetailsbtnComponentShown

    private void pupdatesbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pupdatesbtnComponentShown
//                 if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              pdeletebtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_pupdatesbtnComponentShown

    private void pdeletebtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pdeletebtnComponentShown
//                if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              billingbtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_pdeletebtnComponentShown

    private void emailComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_emailComponentShown
//              if(z==0)
//        {
//            try
//            {
//              Thread.sleep(250);
//              othersbtn.setVisible(true);
//            }
//            catch(Exception e)
//            {
//                
//            }
//        }
    }//GEN-LAST:event_emailComponentShown

    private void logoutbtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_logoutbtnComponentShown
//          }
    }//GEN-LAST:event_logoutbtnComponentShown

    private void bdeletebtnComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_bdeletebtnComponentShown

    }//GEN-LAST:event_bdeletebtnComponentShown

    private void bdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdetailsbtnActionPerformed
       this.setVisible(false);
       new buyer_details_page().setVisible(true);
    }//GEN-LAST:event_bdetailsbtnActionPerformed

    private void bupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bupdatebtnActionPerformed
       this.setVisible(false);
       new Buyer_update_page().setVisible(true);
    }//GEN-LAST:event_bupdatebtnActionPerformed

    private void paddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paddbtnActionPerformed
         this.setVisible(false);
         new Add_product().setVisible(true);
    }//GEN-LAST:event_paddbtnActionPerformed

    private void pdetailsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdetailsbtnActionPerformed
           this.setVisible(false);
         new product_details().setVisible(true);
    }//GEN-LAST:event_pdetailsbtnActionPerformed

    private void pupdatesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pupdatesbtnActionPerformed
        this.setVisible(false);
         new product_updates().setVisible(true);
    }//GEN-LAST:event_pupdatesbtnActionPerformed

    private void pdeletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdeletebtnActionPerformed
        this.setVisible(false);
         new delete_product().setVisible(true);
    }//GEN-LAST:event_pdeletebtnActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        this.setVisible(false);
         new email_page().setVisible(true);
    }//GEN-LAST:event_emailActionPerformed

    private void otpComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_otpComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_otpComponentShown

    private void otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpActionPerformed
        this.setVisible(false);
         new otp().setVisible(true);
    }//GEN-LAST:event_otpActionPerformed

    private void qrComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_qrComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_qrComponentShown

    private void qrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrActionPerformed
       this.setVisible(false);
       new qr_code_page().setVisible(true);
    }//GEN-LAST:event_qrActionPerformed

    private void barchartComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_barchartComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_barchartComponentShown

    private void barchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchartActionPerformed
        this.setVisible(false);
        new barchart_page().setVisible(true);
    }//GEN-LAST:event_barchartActionPerformed

    private void billingbtn4ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_billingbtn4ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_billingbtn4ComponentShown

    private void billingbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billingbtn4ActionPerformed
       this.setVisible(false);
       new billing_page().setVisible(true);
    }//GEN-LAST:event_billingbtn4ActionPerformed

    private void barcodeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_barcodeComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_barcodeComponentShown

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
        this.setVisible(false);
        new barcode_page().setVisible(true);
    }//GEN-LAST:event_barcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baddbtn;
    private javax.swing.JButton barchart;
    private javax.swing.JButton barcode;
    private javax.swing.JButton bdeletebtn;
    private javax.swing.JButton bdetailsbtn;
    private javax.swing.JButton billingbtn4;
    private javax.swing.JButton bupdatebtn;
    private javax.swing.JButton email;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton otp;
    private javax.swing.JButton paddbtn;
    private javax.swing.JButton pdeletebtn;
    private javax.swing.JButton pdetailsbtn;
    private javax.swing.JButton pupdatesbtn;
    private javax.swing.JButton qr;
    // End of variables declaration//GEN-END:variables
}
