/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;
import java.sql.*;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.*;
import jeo_mart.JDBC;
/**
 *
 * @author ASUS
 */
public class product_updates extends javax.swing.JFrame {

    /**
     * Creates new form product_updates
     */
    public product_updates() {
        initComponents();
    }
    public boolean isExists(String id)
    {
        try(Connection conn = JDBC.con();
                PreparedStatement pst = conn.prepareStatement("jemart_product_isExists ?"))
        {
            pst.setString(1, id);
            ResultSet rs = pst.executeQuery();
            if(rs.next())
            {
                return rs.getInt(1)>0;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e); 
        }
        return false;
    }
 public static String decrypt(String encryptedcode , String secretkey) throws Exception
    {
        Cipher cipher = Cipher.getInstance("AES");
        SecretKeySpec  secrectkeyspec = new SecretKeySpec(secretkey.getBytes(),"AES");
        cipher.init(Cipher.DECRYPT_MODE,secrectkeyspec);
        byte[] decodedbyte = Base64.getDecoder().decode(encryptedcode);
        byte[] encryptbyte = cipher.doFinal(decodedbyte);
        return new String(encryptbyte);
    }
  public static String encrypt(String data , String secretkey) throws Exception
    {
        Cipher cipher = Cipher.getInstance("AES");
        SecretKeySpec  secrectkeyspec = new SecretKeySpec(secretkey.getBytes(),"AES");
        cipher.init(Cipher.ENCRYPT_MODE,secrectkeyspec);
        byte[] encryptbyte = cipher.doFinal(data.getBytes());
        return Base64.getEncoder().encodeToString(encryptbyte);
    }
    private final String SECRET_KEY = "1234567890123456";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        update = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pname = new javax.swing.JTextField();
        description = new javax.swing.JTextField();
        price = new javax.swing.JTextField();
        get = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Updates");
        setMaximumSize(new java.awt.Dimension(837, 630));
        setMinimumSize(new java.awt.Dimension(837, 630));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product updates icon.jpg"))); // NOI18N
        jLabel1.setText("PRODUCTS UPDATES");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 6, -1, -1));

        back.setBackground(new java.awt.Color(255, 204, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 18, -1, 32));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(602, 539, 116, 40));

        update.setBackground(new java.awt.Color(0, 204, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 539, 116, 40));

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 539, 116, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCT ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 156, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel3.setText("PRODUCT NAME :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 252, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel4.setText("DESCRIPTION :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 436, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel5.setText("PRICE :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 342, -1, -1));

        pid.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pidKeyPressed(evt);
            }
        });
        getContentPane().add(pid, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 150, 258, 37));

        pname.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 240, 258, 37));

        description.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 430, 258, 37));

        price.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 336, 258, 37));

        get.setBackground(new java.awt.Color(255, 255, 204));
        get.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        get.setText("GET");
        get.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        get.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        get.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getActionPerformed(evt);
            }
        });
        getContentPane().add(get, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 150, 50, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         this.setVisible(false);
        new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        this.setVisible(false);     new product_updates().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        String PID = pid.getText();
        String PNAME = pname.getText();
        String PRICE = price.getText();
        String DESCRIPTION = description.getText();
        if(!PID.isEmpty() && !PNAME.isEmpty() &&  !PRICE.isEmpty() && !DESCRIPTION.isEmpty() )
        {
 
        try(Connection conn = JDBC.con();
                PreparedStatement pst = conn.prepareStatement("jemart_product_update ?,?,?,?"))
        {
         pst.setString(1, PID);
         pst.setString(2, PNAME);
          pst.setString (3,encrypt(PRICE,SECRET_KEY));
           pst.setString(4, DESCRIPTION);
         int result = pst.executeUpdate();
         if(result == 1)
         {
              JOptionPane.showMessageDialog(this,"Datas Updated");
         }
         else
         {
           JOptionPane.showMessageDialog(this,"Datas Can't Update");  
         }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e); 
        }
         }
 
            
            
        
        else
        {
          JOptionPane.showMessageDialog(this,"Enter All Datas");
         }
    }//GEN-LAST:event_updateActionPerformed

    private void pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyPressed
        
          
    
          
        
    }//GEN-LAST:event_pidKeyPressed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void getActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getActionPerformed
        String PID = pid.getText();
        try(Connection conn = JDBC.con();
                PreparedStatement pst = conn.prepareStatement("jemart_product_getbyid ?"))
        {
            pst.setString(1, PID);
            ResultSet rs = pst.executeQuery();
//            if(isExists(PID))
            {
            while(rs.next())
            {
                String PNAME = rs.getString("product_name");
                String PRICE = decrypt(rs.getString("price"),SECRET_KEY);
                String DESCRIPTION = rs.getString("description");
                pname.setText(PNAME);
                price.setText(PRICE);
                description.setText(DESCRIPTION);
            }
        }
//         else
//            {
//               JOptionPane.showMessageDialog(this,"Invalid Product ID");  
//            }
        
}catch(Exception e)
        {
          JOptionPane.showMessageDialog(this,e);    
        }
    }//GEN-LAST:event_getActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_updates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_updates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JTextField description;
    private javax.swing.JButton get;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField price;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
