/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;

import java.awt.print.PrinterException;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.*;
import jeo_mart.JDBC;

/**
 *
 * @author ASUS
 */
public class product_details extends javax.swing.JFrame {

    /**
     * Creates new form product_details
     */
    public product_details() {
        initComponents();
    }
     public static String decrypt(String encryptedcode , String secretkey) throws Exception
    {
        Cipher cipher = Cipher.getInstance("AES");
        SecretKeySpec  secrectkeyspec = new SecretKeySpec(secretkey.getBytes(),"AES");
        cipher.init(Cipher.DECRYPT_MODE,secrectkeyspec);
        byte[] decodedbyte = Base64.getDecoder().decode(encryptedcode);
        byte[] encryptbyte = cipher.doFinal(decodedbyte);
        return new String(encryptbyte);
    }
    private final String SECRET_KEY = "1234567890123456";
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        product_details_tbl = new javax.swing.JTable();
        back = new javax.swing.JButton();
        close = new javax.swing.JButton();
        csv = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        print = new javax.swing.JButton();
        deatils = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Product Details");
        setMaximumSize(new java.awt.Dimension(1109, 585));
        setMinimumSize(new java.awt.Dimension(1109, 585));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product_details_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "PRICE", "DESCRIPTION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(product_details_tbl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 134, 871, 306));

        back.setBackground(new java.awt.Color(255, 204, 102));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<- BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 27, 88, 31));

        close.setBackground(new java.awt.Color(255, 51, 51));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 111, 35));

        csv.setBackground(new java.awt.Color(255, 255, 204));
        csv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        csv.setText("CSV");
        csv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        csv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        csv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvActionPerformed(evt);
            }
        });
        getContentPane().add(csv, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 490, 111, 35));

        clear.setBackground(new java.awt.Color(255, 153, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 111, 35));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/product detail icon.png"))); // NOI18N
        jLabel1.setText("PRODUCT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 6, -1, -1));

        print.setBackground(new java.awt.Color(255, 255, 204));
        print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        print.setText("PRINT");
        print.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 111, 35));

        deatils.setBackground(new java.awt.Color(0, 204, 255));
        deatils.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deatils.setText("DETAILS");
        deatils.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deatils.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deatils.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deatilsActionPerformed(evt);
            }
        });
        getContentPane().add(deatils, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, 111, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 590));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
         this.setVisible(false);
        new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
         this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
         this.setVisible(false); new product_details().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            product_details_tbl.print(JTable.PrintMode.NORMAL);
            JOptionPane.showMessageDialog(this,"Printed Successfully");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void csvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvActionPerformed
        JFileChooser fileChooser = new JFileChooser();
       int userselection =  fileChooser.showSaveDialog(this);
      if(userselection ==JFileChooser.APPROVE_OPTION)
      {
         File filetosave  = fileChooser.getSelectedFile();
         String file = filetosave.getAbsolutePath();
         if(!file.endsWith(".csv"))
         {
             file +=".csv";
         }
         try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {

                for (int i = 0; i < product_details_tbl.getColumnCount(); i++) {
                    writer.write(product_details_tbl.getColumnName(i));
                    if (i < product_details_tbl.getColumnCount() - 1) {
                        writer.write(",");
                    }
                }
                writer.newLine();
         
        for (int row = 0; row < product_details_tbl.getRowCount(); row++) {
                    for (int col = 0; col < product_details_tbl.getColumnCount(); col++) {
                        writer.write(product_details_tbl.getValueAt(row, col).toString());
                        if (col < product_details_tbl.getColumnCount() - 1) {
                            writer.write(",");
                        }
                    }
                    writer.newLine();
                }

                JOptionPane.showMessageDialog(this, "Exported as CSV Successfully");
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }

        }
        else
        {
            JOptionPane.showMessageDialog(this, " Can't Export as CSV Successfully");
        }
      
      
    }//GEN-LAST:event_csvActionPerformed

    private void deatilsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deatilsActionPerformed
        DefaultTableModel model = (DefaultTableModel)product_details_tbl.getModel();
        
        try(Connection conn =JDBC.con();
                PreparedStatement pst = conn.prepareStatement("jemart_product_getall"))
        {
          ResultSet rs = pst.executeQuery();
          model.setRowCount(0);
          while(rs.next())
          {
          String PID  =  rs.getString("product_id");
          String PNAME = rs.getString("product_name");
String PRICE = decrypt(rs.getString("price"),SECRET_KEY);
String DESCRIPTION = rs.getString("description");

 model.addRow( new Object[] {PID,PNAME ,PRICE ,DESCRIPTION });
              
        }
}
            catch(Exception e)
                    {
                    
                    }
        
    }//GEN-LAST:event_deatilsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JButton csv;
    private javax.swing.JButton deatils;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton print;
    private javax.swing.JTable product_details_tbl;
    // End of variables declaration//GEN-END:variables
}
