/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;

import java.awt.image.BufferedImage;
import java.nio.Buffer;
import java.util.Map;
import javax.swing.*;
import com.google.zxing.*;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;
import com.google.zxing.qrcode.decoder.ErrorCorrectionLevel;
import java.io.File;
import java.util.HashMap;
import javax.imageio.ImageIO;

/**
 *
 * @author ASUS
 */
public class qr_code_page extends javax.swing.JFrame {

    /**
     * Creates new form qr_code_page
     */
    public qr_code_page() {
        initComponents();
    }
   private BufferedImage createQRImage(String text,int width,int height) throws Exception
   {
       Map<EncodeHintType,ErrorCorrectionLevel> hints = new HashMap<>();
       hints.put(EncodeHintType.ERROR_CORRECTION, ErrorCorrectionLevel.H);
       QRCodeWriter qrcodewriter = new QRCodeWriter();
       BitMatrix bitMatrix = qrcodewriter.encode(text, BarcodeFormat.QR_CODE, width, height);
       return MatrixToImageWriter.toBufferedImage(bitMatrix);
   }
   private BufferedImage qrImage;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textlbl = new javax.swing.JLabel();
        text = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        qr = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QR Code");
        setMaximumSize(new java.awt.Dimension(826, 519));
        setMinimumSize(new java.awt.Dimension(826, 519));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setText("QR CODE PAGE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<-BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 22, -1, -1));

        clear.setBackground(new java.awt.Color(255, 204, 0));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clear.setText("CLEAR");
        clear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 133, 32));

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        jLabel2.setText("TEXT :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 126, -1, -1));
        getContentPane().add(textlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 216, 194));

        text.setFont(new java.awt.Font("Segoe UI Variable", 1, 18)); // NOI18N
        getContentPane().add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 122, 244, 34));

        close.setBackground(new java.awt.Color(255, 51, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 133, 32));

        qr.setBackground(new java.awt.Color(0, 153, 255));
        qr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        qr.setText("GENERATE_QR");
        qr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrActionPerformed(evt);
            }
        });
        getContentPane().add(qr, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 133, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
       new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       this.setVisible(false);
        new qr_code_page().setVisible(true);
    }//GEN-LAST:event_clearActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
      this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void qrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrActionPerformed
        String text1 = text.getText();
        if(text1.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Enter TExt to get QR-Code");
           return;
        }
        try{
            qrImage = createQRImage(text1,300,300);
            textlbl.setIcon(new ImageIcon(qrImage));
        }
        catch(Exception e)
                {
                 JOptionPane.showMessageDialog(this,e);
                }
        if(textlbl != null)
        {
            JFileChooser fileChooser = new JFileChooser();
            int userselection = fileChooser.showSaveDialog(this);
            if(userselection == JFileChooser.APPROVE_OPTION)
            {
                File filetosave = fileChooser.getSelectedFile();
                try{
                 ImageIO.write(qrImage,"PNG", filetosave);
                 JOptionPane.showMessageDialog(this,"QR-Code Saved");
                }
                catch(Exception e)
                {JOptionPane.showMessageDialog(this,e);
                    
                }
            }
        }
    }//GEN-LAST:event_qrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qr_code_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qr_code_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qr_code_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qr_code_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qr_code_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton qr;
    private javax.swing.JTextField text;
    private javax.swing.JLabel textlbl;
    // End of variables declaration//GEN-END:variables
}
