/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jeo_mart;

/**
 *
 * @author ASUS
 */
public class Utilities extends javax.swing.JFrame {

    /**
     * Creates new form Utilities
     */
    public Utilities() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        barcode = new javax.swing.JButton();
        qrcode = new javax.swing.JButton();
        otp = new javax.swing.JButton();
        barchart = new javax.swing.JButton();
        email = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utilities");
        setMinimumSize(new java.awt.Dimension(658, 648));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/others.png"))); // NOI18N
        jLabel1.setText("UTILITIES...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 6, -1, -1));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        back.setText("<-BACK");
        back.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        barcode.setBackground(new java.awt.Color(255, 204, 204));
        barcode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        barcode.setText("BAR CODE");
        barcode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barcode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barcodeActionPerformed(evt);
            }
        });
        getContentPane().add(barcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 421, 198, 65));

        qrcode.setBackground(new java.awt.Color(255, 204, 204));
        qrcode.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        qrcode.setText("QR CODE");
        qrcode.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        qrcode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        qrcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qrcodeActionPerformed(evt);
            }
        });
        getContentPane().add(qrcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 325, 198, 65));

        otp.setBackground(new java.awt.Color(255, 204, 204));
        otp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        otp.setText("OTP");
        otp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        otp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otpActionPerformed(evt);
            }
        });
        getContentPane().add(otp, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 222, 198, 65));

        barchart.setBackground(new java.awt.Color(255, 204, 204));
        barchart.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        barchart.setText("BAR CHART");
        barchart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barchart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        barchart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barchartActionPerformed(evt);
            }
        });
        getContentPane().add(barchart, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 518, 198, 65));

        email.setBackground(new java.awt.Color(255, 204, 204));
        email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email.setText("EMAIL ");
        email.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 124, 198, 65));

        close.setBackground(new java.awt.Color(255, 0, 0));
        close.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        close.setText("CLOSE");
        close.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 601, 83, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backgrond image.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qrcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qrcodeActionPerformed
       this.setVisible(false);
       new qr_code_page().setVisible(true);
    }//GEN-LAST:event_qrcodeActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       this.setVisible(false);
       new main_page().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        this.setVisible(false);
        new email_page().setVisible(true);
    }//GEN-LAST:event_emailActionPerformed

    private void otpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otpActionPerformed
        this.setVisible(false);
        new otp().setVisible(true);
    }//GEN-LAST:event_otpActionPerformed

    private void barcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barcodeActionPerformed
       this.setVisible(false);
       new barcode_page().setVisible(true);
    }//GEN-LAST:event_barcodeActionPerformed

    private void barchartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barchartActionPerformed
        this.setVisible(false);
        new barchart_page().setVisible(true);
    }//GEN-LAST:event_barchartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Utilities.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Utilities().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton barchart;
    private javax.swing.JButton barcode;
    private javax.swing.JButton close;
    private javax.swing.JButton email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton otp;
    private javax.swing.JButton qrcode;
    // End of variables declaration//GEN-END:variables
}
